name: audio_tagger_flutter
description: Library to read and write ID3 tags to MP3 files. You can get data as Map object or Tag object.
version: 1.0.0
publish_to: none

environment:
  flutter: '>=1.10.0'
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.nicolorebaioli.audiotagger
        pluginClass: AudiotaggerPlugin